/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    adminUsers: AdminUserAuthOperations;
    companyUsers: CompanyUserAuthOperations;
  };
  collections: {
    adminUsers: AdminUser;
    companyUsers: CompanyUser;
    companies: Company;
    contentLanguages: ContentLanguage;
    msdsDocs: MsdsDoc;
    msdsContents: MsdsContent;
    msdsV2: MsdsV2;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    companies: {
      companyUsers: 'companyUsers';
      msdsV2: 'msdsV2';
      msdsContent: 'msdsContents';
    };
  };
  collectionsSelect: {
    adminUsers: AdminUsersSelect<false> | AdminUsersSelect<true>;
    companyUsers: CompanyUsersSelect<false> | CompanyUsersSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    contentLanguages: ContentLanguagesSelect<false> | ContentLanguagesSelect<true>;
    msdsDocs: MsdsDocsSelect<false> | MsdsDocsSelect<true>;
    msdsContents: MsdsContentsSelect<false> | MsdsContentsSelect<true>;
    msdsV2: MsdsV2Select<false> | MsdsV2Select<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'tr' | 'en';
  user:
    | (AdminUser & {
        collection: 'adminUsers';
      })
    | (CompanyUser & {
        collection: 'companyUsers';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CompanyUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Admin Users manage admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminUsers".
 */
export interface AdminUser {
  id: number;
  name?: string | null;
  roles: ('editor' | 'admin')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyUsers".
 */
export interface CompanyUser {
  id: number;
  email: string;
  hashedPassword?: string | null;
  /**
   * The information required to complete the account creation process is sent to the user's email address after the creation process.
   */
  sendEmail?: boolean | null;
  registrationCompleted?: boolean | null;
  fullname: string;
  personalPhoneNumber: string;
  position?: string | null;
  company: number | Company;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  companyName: string;
  status?: ('active' | 'passive') | null;
  email: string;
  address: string;
  phoneNumber: string;
  taxNumber?: string | null;
  taxOffice?: string | null;
  tradeRegistryNumber?: string | null;
  mersisNumber?: string | null;
  country?:
    | (
        | 'AF'
        | 'AX'
        | 'AL'
        | 'DZ'
        | 'AS'
        | 'AD'
        | 'AO'
        | 'AI'
        | 'AQ'
        | 'AG'
        | 'AR'
        | 'AM'
        | 'AW'
        | 'AU'
        | 'AT'
        | 'AZ'
        | 'BS'
        | 'BH'
        | 'BD'
        | 'BB'
        | 'BY'
        | 'BE'
        | 'BZ'
        | 'BJ'
        | 'BM'
        | 'BT'
        | 'BO'
        | 'BA'
        | 'BW'
        | 'BV'
        | 'BR'
        | 'IO'
        | 'BN'
        | 'BG'
        | 'BF'
        | 'BI'
        | 'KH'
        | 'CM'
        | 'CA'
        | 'CV'
        | 'KY'
        | 'CF'
        | 'TD'
        | 'CL'
        | 'CN'
        | 'CX'
        | 'CC'
        | 'CO'
        | 'KM'
        | 'CG'
        | 'CD'
        | 'CK'
        | 'CR'
        | 'CI'
        | 'HR'
        | 'CU'
        | 'CY'
        | 'CZ'
        | 'DK'
        | 'DJ'
        | 'DM'
        | 'DO'
        | 'TL'
        | 'EC'
        | 'EG'
        | 'SV'
        | 'GQ'
        | 'ER'
        | 'EE'
        | 'ET'
        | 'FK'
        | 'FO'
        | 'FJ'
        | 'FI'
        | 'FR'
        | 'GF'
        | 'PF'
        | 'TF'
        | 'GA'
        | 'GM'
        | 'GE'
        | 'DE'
        | 'GH'
        | 'GI'
        | 'GR'
        | 'GL'
        | 'GD'
        | 'GP'
        | 'GU'
        | 'GT'
        | 'GG'
        | 'GN'
        | 'GW'
        | 'GY'
        | 'HT'
        | 'HM'
        | 'HN'
        | 'HK'
        | 'HU'
        | 'IS'
        | 'IN'
        | 'ID'
        | 'IR'
        | 'IQ'
        | 'IE'
        | 'IL'
        | 'IT'
        | 'JM'
        | 'JP'
        | 'JE'
        | 'JO'
        | 'KZ'
        | 'KE'
        | 'KI'
        | 'KP'
        | 'KR'
        | 'KW'
        | 'KG'
        | 'LA'
        | 'LV'
        | 'LB'
        | 'LS'
        | 'LR'
        | 'LY'
        | 'LI'
        | 'LT'
        | 'LU'
        | 'MO'
        | 'MK'
        | 'MG'
        | 'MW'
        | 'MY'
        | 'MV'
        | 'ML'
        | 'MT'
        | 'IM'
        | 'MH'
        | 'MQ'
        | 'MR'
        | 'MU'
        | 'YT'
        | 'MX'
        | 'FM'
        | 'MD'
        | 'MC'
        | 'MN'
        | 'ME'
        | 'MS'
        | 'MA'
        | 'MZ'
        | 'MM'
        | 'NA'
        | 'NR'
        | 'NP'
        | 'BQ'
        | 'NL'
        | 'NC'
        | 'NZ'
        | 'NI'
        | 'NE'
        | 'NG'
        | 'NU'
        | 'NF'
        | 'MP'
        | 'NO'
        | 'OM'
        | 'PK'
        | 'PW'
        | 'PS'
        | 'PA'
        | 'PG'
        | 'PY'
        | 'PE'
        | 'PH'
        | 'PN'
        | 'PL'
        | 'PT'
        | 'PR'
        | 'QA'
        | 'RE'
        | 'RO'
        | 'RU'
        | 'RW'
        | 'SH'
        | 'KN'
        | 'LC'
        | 'PM'
        | 'VC'
        | 'BL'
        | 'MF'
        | 'WS'
        | 'SM'
        | 'ST'
        | 'SA'
        | 'SN'
        | 'RS'
        | 'SC'
        | 'SL'
        | 'SG'
        | 'SK'
        | 'SI'
        | 'SB'
        | 'SO'
        | 'ZA'
        | 'GS'
        | 'SS'
        | 'ES'
        | 'LK'
        | 'SD'
        | 'SR'
        | 'SJ'
        | 'SZ'
        | 'SE'
        | 'CH'
        | 'SY'
        | 'TW'
        | 'TJ'
        | 'TZ'
        | 'TH'
        | 'TG'
        | 'TK'
        | 'TO'
        | 'TT'
        | 'TN'
        | 'TR'
        | 'TM'
        | 'TC'
        | 'TV'
        | 'UG'
        | 'UA'
        | 'AE'
        | 'GB'
        | 'US'
        | 'UM'
        | 'UY'
        | 'UZ'
        | 'VU'
        | 'VA'
        | 'VE'
        | 'VN'
        | 'VG'
        | 'VI'
        | 'WF'
        | 'EH'
        | 'YE'
        | 'ZM'
        | 'ZW'
        | 'XK'
        | 'CW'
        | 'SX'
      )
    | null;
  state?: string | null;
  city?: string | null;
  companyUsers?: {
    docs?: (number | CompanyUser)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  msdsV2?: {
    docs?: (number | MsdsV2)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  /**
   * This field will be deprecated. Use MSDS v2 instead.
   */
  msdsContent?: {
    docs?: (number | MsdsContent)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Use this to manage MSDS contents. "MSDS Files" and "MSDS Records" will be deprecated soon. Use MSDS v2 instead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "msdsV2".
 */
export interface MsdsV2 {
  id: number;
  /**
   * If not filled, it takes the name of the uploaded file.
   */
  name?: string | null;
  /**
   * Automatically generated after saving the document. (It is defined as: {company}-{name}-{id}-{contentLanguage})
   */
  uniqueId?: string | null;
  company: number | Company;
  /**
   * Determine whether the content can currently be displayed to the customer.
   */
  isPublished?: boolean | null;
  /**
   * If there are fields that are not filled, it will read them from the pdf file and fill them automatically.
   */
  aiScanning?: boolean | null;
  msdsCreatedAt?: string | null;
  formNo?: string | null;
  msdsUpdatedAt?: string | null;
  updatedCount?: number | null;
  author?: string | null;
  certificateDate?: string | null;
  contentLanguage?: (number | null) | ContentLanguage;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentLanguages".
 */
export interface ContentLanguage {
  id: number;
  name: string;
  code: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "msdsContents".
 */
export interface MsdsContent {
  id: number;
  name: string;
  company: number | Company;
  /**
   * You can add MSDS content for each language option.
   */
  msdsContent: {
    msdsFile: number | MsdsDoc;
    msdsLanguage:
      | 'aa'
      | 'aa-DJ'
      | 'aa-ER'
      | 'aa-ET'
      | 'af'
      | 'af-NA'
      | 'af-ZA'
      | 'agq'
      | 'agq-CM'
      | 'ak'
      | 'ak-GH'
      | 'sq'
      | 'sq-AL'
      | 'sq-MK'
      | 'gsw'
      | 'gsw-FR'
      | 'gsw-LI'
      | 'gsw-CH'
      | 'am'
      | 'am-ET'
      | 'ar'
      | 'ar-DZ'
      | 'ar-BH'
      | 'ar-TD'
      | 'ar-KM'
      | 'ar-DJ'
      | 'ar-EG'
      | 'ar-ER'
      | 'ar-IQ'
      | 'ar-IL'
      | 'ar-JO'
      | 'ar-KW'
      | 'ar-LB'
      | 'ar-LY'
      | 'ar-MR'
      | 'ar-MA'
      | 'ar-OM'
      | 'ar-PS'
      | 'ar-QA'
      | 'ar-SA'
      | 'ar-SO'
      | 'ar-SS'
      | 'ar-SD'
      | 'ar-SY'
      | 'ar-TN'
      | 'ar-AE'
      | 'ar-001'
      | 'ar-YE'
      | 'hy'
      | 'hy-AM'
      | 'as'
      | 'as-IN'
      | 'ast'
      | 'ast-ES'
      | 'asa'
      | 'asa-TZ'
      | 'az-Cyrl'
      | 'az-Cyrl-AZ'
      | 'az'
      | 'az-Latn'
      | 'az-Latn-AZ'
      | 'ksf'
      | 'ksf-CM'
      | 'bm'
      | 'bm-Latn-ML'
      | 'bn'
      | 'bn-BD'
      | 'bn-IN'
      | 'bas'
      | 'bas-CM'
      | 'ba'
      | 'ba-RU'
      | 'eu'
      | 'eu-ES'
      | 'be'
      | 'be-BY'
      | 'bem'
      | 'bem-ZM'
      | 'bez'
      | 'bez-TZ'
      | 'byn'
      | 'byn-ER'
      | 'brx'
      | 'brx-IN'
      | 'bs-Cyrl'
      | 'bs-Cyrl-BA'
      | 'bs-Latn'
      | 'bs'
      | 'bs-Latn-BA'
      | 'br'
      | 'br-FR'
      | 'bg'
      | 'bg-BG'
      | 'my'
      | 'my-MM'
      | 'ca'
      | 'ca-AD'
      | 'ca-FR'
      | 'ca-IT'
      | 'ca-ES'
      | 'ceb'
      | 'ceb-Latn'
      | 'ceb-Latn-PH'
      | 'tzm-Latn-'
      | 'ku'
      | 'ku-Arab'
      | 'ku-Arab-IQ'
      | 'ccp'
      | 'ccp-Cakm'
      | 'ccp-Cakm-'
      | 'cd-RU'
      | 'chr'
      | 'chr-Cher'
      | 'chr-Cher-US'
      | 'cgg'
      | 'cgg-UG'
      | 'zh-Hans'
      | 'zh'
      | 'zh-CN'
      | 'zh-SG'
      | 'zh-Hant'
      | 'zh-HK'
      | 'zh-MO'
      | 'zh-TW'
      | 'cu-RU'
      | 'swc'
      | 'swc-CD'
      | 'kw'
      | 'kw-GB'
      | 'co'
      | 'co-FR'
      | 'hr'
      | 'hr-HR'
      | 'hr-BA'
      | 'cs'
      | 'cs-CZ'
      | 'da'
      | 'da-DK'
      | 'da-GL'
      | 'prs'
      | 'prs-AF'
      | 'dv'
      | 'dv-MV'
      | 'dua'
      | 'dua-CM'
      | 'nl'
      | 'nl-AW'
      | 'nl-BE'
      | 'nl-BQ'
      | 'nl-CW'
      | 'nl-NL'
      | 'nl-SX'
      | 'nl-SR'
      | 'dz'
      | 'dz-BT'
      | 'ebu'
      | 'ebu-KE'
      | 'en'
      | 'en-AS'
      | 'en-AI'
      | 'en-AG'
      | 'en-AU'
      | 'en-AT'
      | 'en-BS'
      | 'en-BB'
      | 'en-BE'
      | 'en-BZ'
      | 'en-BM'
      | 'en-BW'
      | 'en-IO'
      | 'en-VG'
      | 'en-BI'
      | 'en-CM'
      | 'en-CA'
      | 'en-029'
      | 'en-KY'
      | 'en-CX'
      | 'en-CC'
      | 'en-CK'
      | 'en-CY'
      | 'en-DK'
      | 'en-DM'
      | 'en-ER'
      | 'en-150'
      | 'en-FK'
      | 'en-FI'
      | 'en-FJ'
      | 'en-GM'
      | 'en-DE'
      | 'en-GH'
      | 'en-GI'
      | 'en-GD'
      | 'en-GU'
      | 'en-GG'
      | 'en-GY'
      | 'en-HK'
      | 'en-IN'
      | 'en-IE'
      | 'en-IM'
      | 'en-IL'
      | 'en-JM'
      | 'en-JE'
      | 'en-KE'
      | 'en-KI'
      | 'en-LS'
      | 'en-LR'
      | 'en-MO'
      | 'en-MG'
      | 'en-MW'
      | 'en-MY'
      | 'en-MT'
      | 'en-MH'
      | 'en-MU'
      | 'en-FM'
      | 'en-MS'
      | 'en-NA'
      | 'en-NR'
      | 'en-NL'
      | 'en-NZ'
      | 'en-NG'
      | 'en-NU'
      | 'en-NF'
      | 'en-MP'
      | 'en-PK'
      | 'en-PW'
      | 'en-PG'
      | 'en-PN'
      | 'en-PR'
      | 'en-PH'
      | 'en-RW'
      | 'en-KN'
      | 'en-LC'
      | 'en-VC'
      | 'en-WS'
      | 'en-SC'
      | 'en-SL'
      | 'en-SG'
      | 'en-SX'
      | 'en-SI'
      | 'en-SB'
      | 'en-ZA'
      | 'en-SS'
      | 'en-SH'
      | 'en-SD'
      | 'en-SZ'
      | 'en-SE'
      | 'en-CH'
      | 'en-TZ'
      | 'en-TK'
      | 'en-TO'
      | 'en-TT'
      | 'en-TC'
      | 'en-TV'
      | 'en-UG'
      | 'en-AE'
      | 'en-GB'
      | 'en-US'
      | 'en-UM'
      | 'en-VI'
      | 'en-VU'
      | 'en-001'
      | 'en-ZM'
      | 'en-ZW'
      | 'eo'
      | 'eo-001'
      | 'et'
      | 'et-EE'
      | 'ee'
      | 'ee-GH'
      | 'ee-TG'
      | 'ewo'
      | 'ewo-CM'
      | 'fo'
      | 'fo-DK'
      | 'fo-FO'
      | 'fil'
      | 'fil-PH'
      | 'fi'
      | 'fi-FI'
      | 'fr'
      | 'fr-DZ'
      | 'fr-BE'
      | 'fr-BJ'
      | 'fr-BF'
      | 'fr-BI'
      | 'fr-CM'
      | 'fr-CA'
      | 'fr-CF'
      | 'fr-TD'
      | 'fr-KM'
      | 'fr-CG'
      | 'fr-CD'
      | 'fr-CI'
      | 'fr-DJ'
      | 'fr-GQ'
      | 'fr-FR'
      | 'fr-GF'
      | 'fr-PF'
      | 'fr-GA'
      | 'fr-GP'
      | 'fr-GN'
      | 'fr-HT'
      | 'fr-LU'
      | 'fr-MG'
      | 'fr-ML'
      | 'fr-MQ'
      | 'fr-MR'
      | 'fr-MU'
      | 'fr-YT'
      | 'fr-MA'
      | 'fr-NC'
      | 'fr-NE'
      | 'fr-MC'
      | 'fr-RE'
      | 'fr-RW'
      | 'fr-BL'
      | 'fr-MF'
      | 'fr-PM'
      | 'fr-SN'
      | 'fr-SC'
      | 'fr-CH'
      | 'fr-SY'
      | 'fr-TG'
      | 'fr-TN'
      | 'fr-VU'
      | 'fr-WF'
      | 'fy'
      | 'fy-NL'
      | 'fur'
      | 'fur-IT'
      | 'ff'
      | 'ff-Latn'
      | 'ff-Latn-BF'
      | 'ff-CM'
      | 'ff-Latn-CM'
      | 'ff-Latn-GM'
      | 'ff-Latn-GH'
      | 'ff-GN'
      | 'ff-Latn-GN'
      | 'ff-Latn-GW'
      | 'ff-Latn-LR'
      | 'ff-MR'
      | 'ff-Latn-MR'
      | 'ff-Latn-NE'
      | 'ff-NG'
      | 'ff-Latn-NG'
      | 'ff-Latn-SN'
      | 'ff-Latn-SL'
      | 'gl'
      | 'gl-ES'
      | 'lg'
      | 'lg-UG'
      | 'ka'
      | 'ka-GE'
      | 'de'
      | 'de-AT'
      | 'de-BE'
      | 'de-DE'
      | 'de-IT'
      | 'de-LI'
      | 'de-LU'
      | 'de-CH'
      | 'el'
      | 'el-CY'
      | 'el-GR'
      | 'kl'
      | 'kl-GL'
      | 'gn'
      | 'gn-PY'
      | 'gu'
      | 'gu-IN'
      | 'guz'
      | 'guz-KE'
      | 'ha'
      | 'ha-Latn'
      | 'ha-Latn-GH'
      | 'ha-Latn-NE'
      | 'ha-Latn-NG'
      | 'haw'
      | 'haw-US'
      | 'he'
      | 'he-IL'
      | 'hi'
      | 'hi-IN'
      | 'hu'
      | 'hu-HU'
      | 'is'
      | 'is-IS'
      | 'ig'
      | 'ig-NG'
      | 'id'
      | 'id-ID'
      | 'ia'
      | 'ia-FR'
      | 'ia-001'
      | 'iu'
      | 'iu-Latn'
      | 'iu-Latn-CA'
      | 'iu-Cans'
      | 'iu-Cans-CA'
      | 'ga'
      | 'ga-IE'
      | 'it'
      | 'it-IT'
      | 'it-SM'
      | 'it-CH'
      | 'it-VA'
      | 'ja'
      | 'ja-JP'
      | 'jv'
      | 'jv-Latn'
      | 'jv-Latn-ID'
      | 'dyo'
      | 'dyo-SN'
      | 'kea'
      | 'kea-CV'
      | 'kab'
      | 'kab-DZ'
      | 'kkj'
      | 'kkj-CM'
      | 'kln'
      | 'kln-KE'
      | 'kam'
      | 'kam-KE'
      | 'kn'
      | 'kn-IN'
      | 'ks'
      | 'ks-Arab'
      | 'ks-Arab-IN'
      | 'kk'
      | 'kk-KZ'
      | 'km'
      | 'km-KH'
      | 'quc'
      | 'quc-Latn-GT'
      | 'ki'
      | 'ki-KE'
      | 'rw'
      | 'rw-RW'
      | 'sw'
      | 'sw-KE'
      | 'sw-TZ'
      | 'sw-UG'
      | 'kok'
      | 'kok-IN'
      | 'ko'
      | 'ko-KR'
      | 'ko-KP'
      | 'khq'
      | 'khq-ML'
      | 'ses'
      | 'ses-ML'
      | 'nmg'
      | 'nmg-CM'
      | 'ky'
      | 'ky-KG'
      | 'ku-Arab-IR'
      | 'lkt'
      | 'lkt-US'
      | 'lag'
      | 'lag-TZ'
      | 'lo'
      | 'lo-LA'
      | 'lv'
      | 'lv-LV'
      | 'ln'
      | 'ln-AO'
      | 'ln-CF'
      | 'ln-CG'
      | 'ln-CD'
      | 'lt'
      | 'lt-LT'
      | 'nds'
      | 'nds-DE'
      | 'nds-NL'
      | 'dsb'
      | 'dsb-DE'
      | 'lu'
      | 'lu-CD'
      | 'luo'
      | 'luo-KE'
      | 'lb'
      | 'lb-LU'
      | 'luy'
      | 'luy-KE'
      | 'mk'
      | 'mk-MK'
      | 'jmc'
      | 'jmc-TZ'
      | 'mgh'
      | 'mgh-MZ'
      | 'kde'
      | 'kde-TZ'
      | 'mg'
      | 'mg-MG'
      | 'ms'
      | 'ms-BN'
      | 'ms-MY'
      | 'ml'
      | 'ml-IN'
      | 'mt'
      | 'mt-MT'
      | 'gv'
      | 'gv-IM'
      | 'mi'
      | 'mi-NZ'
      | 'arn'
      | 'arn-CL'
      | 'mr'
      | 'mr-IN'
      | 'mas'
      | 'mas-KE'
      | 'mas-TZ'
      | 'mzn-IR'
      | 'mer'
      | 'mer-KE'
      | 'mgo'
      | 'mgo-CM'
      | 'moh'
      | 'moh-CA'
      | 'mn'
      | 'mn-Cyrl'
      | 'mn-MN'
      | 'mn-Mong'
      | 'mn-Mong-CN'
      | 'mn-Mong-MN'
      | 'mfe'
      | 'mfe-MU'
      | 'mua'
      | 'mua-CM'
      | 'nqo'
      | 'nqo-GN'
      | 'naq'
      | 'naq-NA'
      | 'ne'
      | 'ne-IN'
      | 'ne-NP'
      | 'nnh'
      | 'nnh-CM'
      | 'jgo'
      | 'jgo-CM'
      | 'lrc-IQ'
      | 'lrc-IR'
      | 'nd'
      | 'nd-ZW'
      | 'no'
      | 'nb'
      | 'nb-NO'
      | 'nn'
      | 'nn-NO'
      | 'nb-SJ'
      | 'nus'
      | 'nus-SD'
      | 'nus-SS'
      | 'nyn'
      | 'nyn-UG'
      | 'oc'
      | 'oc-FR'
      | 'or'
      | 'or-IN'
      | 'om'
      | 'om-ET'
      | 'om-KE'
      | 'os'
      | 'os-GE'
      | 'os-RU'
      | 'ps'
      | 'ps-AF'
      | 'ps-PK'
      | 'fa'
      | 'fa-AF'
      | 'fa-IR'
      | 'pl'
      | 'pl-PL'
      | 'pt'
      | 'pt-AO'
      | 'pt-BR'
      | 'pt-CV'
      | 'pt-GQ'
      | 'pt-GW'
      | 'pt-LU'
      | 'pt-MO'
      | 'pt-MZ'
      | 'pt-PT'
      | 'pt-ST'
      | 'pt-CH'
      | 'pt-TL'
      | 'prg-001'
      | 'qps-ploca'
      | 'qps-ploc'
      | 'qps-plocm'
      | 'pa'
      | 'pa-Arab'
      | 'pa-IN'
      | 'pa-Arab-PK'
      | 'quz'
      | 'quz-BO'
      | 'quz-EC'
      | 'quz-PE'
      | 'ksh'
      | 'ksh-DE'
      | 'ro'
      | 'ro-MD'
      | 'ro-RO'
      | 'rm'
      | 'rm-CH'
      | 'rof'
      | 'rof-TZ'
      | 'rn'
      | 'rn-BI'
      | 'ru'
      | 'ru-BY'
      | 'ru-KZ'
      | 'ru-KG'
      | 'ru-MD'
      | 'ru-RU'
      | 'ru-UA'
      | 'rwk'
      | 'rwk-TZ'
      | 'ssy'
      | 'ssy-ER'
      | 'sah'
      | 'sah-RU'
      | 'saq'
      | 'saq-KE'
      | 'smn'
      | 'smn-FI'
      | 'smj'
      | 'smj-NO'
      | 'smj-SE'
      | 'se'
      | 'se-FI'
      | 'se-NO'
      | 'se-SE'
      | 'sms'
      | 'sms-FI'
      | 'sma'
      | 'sma-NO'
      | 'sma-SE'
      | 'sg'
      | 'sg-CF'
      | 'sbp'
      | 'sbp-TZ'
      | 'sa'
      | 'sa-IN'
      | 'gd'
      | 'gd-GB'
      | 'seh'
      | 'seh-MZ'
      | 'sr-Cyrl'
      | 'sr-Cyrl-BA'
      | 'sr-Cyrl-ME'
      | 'sr-Cyrl-RS'
      | 'sr-Cyrl-CS'
      | 'sr-Latn'
      | 'sr'
      | 'sr-Latn-BA'
      | 'sr-Latn-ME'
      | 'sr-Latn-RS'
      | 'sr-Latn-CS'
      | 'nso'
      | 'nso-ZA'
      | 'tn'
      | 'tn-BW'
      | 'tn-ZA'
      | 'ksb'
      | 'ksb-TZ'
      | 'sn'
      | 'sn-Latn'
      | 'sn-Latn-ZW'
      | 'sd'
      | 'sd-Arab'
      | 'sd-Arab-PK'
      | 'si'
      | 'si-LK'
      | 'sk'
      | 'sk-SK'
      | 'sl'
      | 'sl-SI'
      | 'xog'
      | 'xog-UG'
      | 'so'
      | 'so-DJ'
      | 'so-ET'
      | 'so-KE'
      | 'so-SO'
      | 'st'
      | 'st-ZA'
      | 'nr'
      | 'nr-ZA'
      | 'st-LS'
      | 'es'
      | 'es-AR'
      | 'es-BZ'
      | 'es-VE'
      | 'es-BO'
      | 'es-BR'
      | 'es-CL'
      | 'es-CO'
      | 'es-CR'
      | 'es-CU'
      | 'es-DO'
      | 'es-EC'
      | 'es-SV'
      | 'es-GQ'
      | 'es-GT'
      | 'es-HN'
      | 'es-419'
      | 'es-MX'
      | 'es-NI'
      | 'es-PA'
      | 'es-PY'
      | 'es-PE'
      | 'es-PH'
      | 'es-PR'
      | 'es-ES_tradnl'
      | 'es-ES'
      | 'es-US'
      | 'es-UY'
      | 'zgh'
      | 'zgh-Tfng-MA'
      | 'zgh-Tfng'
      | 'ss'
      | 'ss-ZA'
      | 'ss-SZ'
      | 'sv'
      | 'sv-AX'
      | 'sv-FI'
      | 'sv-SE'
      | 'syr'
      | 'syr-SY'
      | 'shi'
      | 'shi-Tfng'
      | 'shi-Tfng-MA'
      | 'shi-Latn'
      | 'shi-Latn-MA'
      | 'dav'
      | 'dav-KE'
      | 'tg'
      | 'tg-Cyrl'
      | 'tg-Cyrl-TJ'
      | 'tzm'
      | 'tzm-Latn'
      | 'tzm-Latn-DZ'
      | 'ta'
      | 'ta-IN'
      | 'ta-MY'
      | 'ta-SG'
      | 'ta-LK'
      | 'twq'
      | 'twq-NE'
      | 'tt'
      | 'tt-RU'
      | 'te'
      | 'te-IN'
      | 'teo'
      | 'teo-KE'
      | 'teo-UG'
      | 'th'
      | 'th-TH'
      | 'bo'
      | 'bo-IN'
      | 'bo-CN'
      | 'tig'
      | 'tig-ER'
      | 'ti'
      | 'ti-ER'
      | 'ti-ET'
      | 'to'
      | 'to-TO'
      | 'ts'
      | 'ts-ZA'
      | 'tr'
      | 'tr-CY'
      | 'tr-TR'
      | 'tk'
      | 'tk-TM'
      | 'uk'
      | 'uk-UA'
      | 'hsb'
      | 'hsb-DE'
      | 'ur'
      | 'ur-IN'
      | 'ur-PK'
      | 'ug'
      | 'ug-CN'
      | 'uz-Arab'
      | 'uz-Arab-AF'
      | 'uz-Cyrl'
      | 'uz-Cyrl-UZ'
      | 'uz'
      | 'uz-Latn'
      | 'uz-Latn-UZ'
      | 'vai'
      | 'vai-Vaii'
      | 'vai-Vaii-LR'
      | 'vai-Latn-LR'
      | 'vai-Latn'
      | 'ca-ES-'
      | 've'
      | 've-ZA'
      | 'vi'
      | 'vi-VN'
      | 'vo'
      | 'vo-001'
      | 'vun'
      | 'vun-TZ'
      | 'wae'
      | 'wae-CH'
      | 'cy'
      | 'cy-GB'
      | 'wal'
      | 'wal-ET'
      | 'wo'
      | 'wo-SN'
      | 'xh'
      | 'xh-ZA'
      | 'yav'
      | 'yav-CM'
      | 'ii'
      | 'ii-CN'
      | 'yo'
      | 'yo-BJ'
      | 'yo-NG'
      | 'dje'
      | 'dje-NE'
      | 'zu'
      | 'zu-ZA';
    /**
     * It is a unique id generated for the MSDS content you add. It is created according to these combinations: {msdsCompanyName}-{msdsId}-{msdsName}-{msdsContentId}-{msdsContentLanguage}. If any of these changes, the id will be updated.
     */
    msdsUniuqeId?: string | null;
    id?: string | null;
  }[];
  publishedAt?: string | null;
  /**
   * Determine whether the content can currently be displayed.
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "msdsDocs".
 */
export interface MsdsDoc {
  id: number;
  /**
   * Fills the document automaticlly after saving. (Ai scanning & filling)
   */
  preparation_date?: string | null;
  /**
   * Fills the document automaticlly after saving. (Ai scanning & filling)
   */
  form_no?: string | null;
  /**
   * Fills the document automaticlly after saving. (Ai scanning & filling)
   */
  new_regulation_date?: string | null;
  /**
   * Fills the document automaticlly after saving. (Ai scanning & filling)
   */
  how_many_regulations?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'adminUsers';
        value: number | AdminUser;
      } | null)
    | ({
        relationTo: 'companyUsers';
        value: number | CompanyUser;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'contentLanguages';
        value: number | ContentLanguage;
      } | null)
    | ({
        relationTo: 'msdsDocs';
        value: number | MsdsDoc;
      } | null)
    | ({
        relationTo: 'msdsContents';
        value: number | MsdsContent;
      } | null)
    | ({
        relationTo: 'msdsV2';
        value: number | MsdsV2;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'adminUsers';
        value: number | AdminUser;
      }
    | {
        relationTo: 'companyUsers';
        value: number | CompanyUser;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'adminUsers';
        value: number | AdminUser;
      }
    | {
        relationTo: 'companyUsers';
        value: number | CompanyUser;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminUsers_select".
 */
export interface AdminUsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyUsers_select".
 */
export interface CompanyUsersSelect<T extends boolean = true> {
  email?: T;
  hashedPassword?: T;
  sendEmail?: T;
  registrationCompleted?: T;
  fullname?: T;
  personalPhoneNumber?: T;
  position?: T;
  company?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  companyName?: T;
  status?: T;
  email?: T;
  address?: T;
  phoneNumber?: T;
  taxNumber?: T;
  taxOffice?: T;
  tradeRegistryNumber?: T;
  mersisNumber?: T;
  country?: T;
  state?: T;
  city?: T;
  companyUsers?: T;
  msdsV2?: T;
  msdsContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentLanguages_select".
 */
export interface ContentLanguagesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "msdsDocs_select".
 */
export interface MsdsDocsSelect<T extends boolean = true> {
  preparation_date?: T;
  form_no?: T;
  new_regulation_date?: T;
  how_many_regulations?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "msdsContents_select".
 */
export interface MsdsContentsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  msdsContent?:
    | T
    | {
        msdsFile?: T;
        msdsLanguage?: T;
        msdsUniuqeId?: T;
        id?: T;
      };
  publishedAt?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "msdsV2_select".
 */
export interface MsdsV2Select<T extends boolean = true> {
  name?: T;
  uniqueId?: T;
  company?: T;
  isPublished?: T;
  aiScanning?: T;
  msdsCreatedAt?: T;
  formNo?: T;
  msdsUpdatedAt?: T;
  updatedCount?: T;
  author?: T;
  certificateDate?: T;
  contentLanguage?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}