/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    adminUsers: AdminUserAuthOperations;
    companyUsers: CompanyUserAuthOperations;
  };
  collections: {
    adminUsers: AdminUser;
    companyUsers: CompanyUser;
    companies: Company;
    contentLanguages: ContentLanguage;
    msdsV2: MsdsV2;
    msdsRequests: MsdsRequest;
    fileMedia: FileMedia;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    companies: {
      companyUsers: 'companyUsers';
      msdsV2: 'msdsV2';
    };
  };
  collectionsSelect: {
    adminUsers: AdminUsersSelect<false> | AdminUsersSelect<true>;
    companyUsers: CompanyUsersSelect<false> | CompanyUsersSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    contentLanguages: ContentLanguagesSelect<false> | ContentLanguagesSelect<true>;
    msdsV2: MsdsV2Select<false> | MsdsV2Select<true>;
    msdsRequests: MsdsRequestsSelect<false> | MsdsRequestsSelect<true>;
    fileMedia: FileMediaSelect<false> | FileMediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'tr' | 'en';
  user:
    | (AdminUser & {
        collection: 'adminUsers';
      })
    | (CompanyUser & {
        collection: 'companyUsers';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CompanyUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Admin Users manage admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminUsers".
 */
export interface AdminUser {
  id: number;
  name?: string | null;
  roles: ('editor' | 'admin')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyUsers".
 */
export interface CompanyUser {
  id: number;
  email: string;
  hashedPassword?: string | null;
  /**
   * The information required to complete the account creation process is sent to the user's email address after the creation process.
   */
  sendEmail?: boolean | null;
  registrationCompleted?: boolean | null;
  fullname: string;
  personalPhoneNumber: string;
  position?: string | null;
  company: number | Company;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  companyName: string;
  status?: ('active' | 'passive') | null;
  email: string;
  address: string;
  phoneNumber: string;
  taxNumber?: string | null;
  taxOffice?: string | null;
  tradeRegistryNumber?: string | null;
  mersisNumber?: string | null;
  country?:
    | (
        | 'AF'
        | 'AX'
        | 'AL'
        | 'DZ'
        | 'AS'
        | 'AD'
        | 'AO'
        | 'AI'
        | 'AQ'
        | 'AG'
        | 'AR'
        | 'AM'
        | 'AW'
        | 'AU'
        | 'AT'
        | 'AZ'
        | 'BS'
        | 'BH'
        | 'BD'
        | 'BB'
        | 'BY'
        | 'BE'
        | 'BZ'
        | 'BJ'
        | 'BM'
        | 'BT'
        | 'BO'
        | 'BA'
        | 'BW'
        | 'BV'
        | 'BR'
        | 'IO'
        | 'BN'
        | 'BG'
        | 'BF'
        | 'BI'
        | 'KH'
        | 'CM'
        | 'CA'
        | 'CV'
        | 'KY'
        | 'CF'
        | 'TD'
        | 'CL'
        | 'CN'
        | 'CX'
        | 'CC'
        | 'CO'
        | 'KM'
        | 'CG'
        | 'CD'
        | 'CK'
        | 'CR'
        | 'CI'
        | 'HR'
        | 'CU'
        | 'CY'
        | 'CZ'
        | 'DK'
        | 'DJ'
        | 'DM'
        | 'DO'
        | 'TL'
        | 'EC'
        | 'EG'
        | 'SV'
        | 'GQ'
        | 'ER'
        | 'EE'
        | 'ET'
        | 'FK'
        | 'FO'
        | 'FJ'
        | 'FI'
        | 'FR'
        | 'GF'
        | 'PF'
        | 'TF'
        | 'GA'
        | 'GM'
        | 'GE'
        | 'DE'
        | 'GH'
        | 'GI'
        | 'GR'
        | 'GL'
        | 'GD'
        | 'GP'
        | 'GU'
        | 'GT'
        | 'GG'
        | 'GN'
        | 'GW'
        | 'GY'
        | 'HT'
        | 'HM'
        | 'HN'
        | 'HK'
        | 'HU'
        | 'IS'
        | 'IN'
        | 'ID'
        | 'IR'
        | 'IQ'
        | 'IE'
        | 'IL'
        | 'IT'
        | 'JM'
        | 'JP'
        | 'JE'
        | 'JO'
        | 'KZ'
        | 'KE'
        | 'KI'
        | 'KP'
        | 'KR'
        | 'KW'
        | 'KG'
        | 'LA'
        | 'LV'
        | 'LB'
        | 'LS'
        | 'LR'
        | 'LY'
        | 'LI'
        | 'LT'
        | 'LU'
        | 'MO'
        | 'MK'
        | 'MG'
        | 'MW'
        | 'MY'
        | 'MV'
        | 'ML'
        | 'MT'
        | 'IM'
        | 'MH'
        | 'MQ'
        | 'MR'
        | 'MU'
        | 'YT'
        | 'MX'
        | 'FM'
        | 'MD'
        | 'MC'
        | 'MN'
        | 'ME'
        | 'MS'
        | 'MA'
        | 'MZ'
        | 'MM'
        | 'NA'
        | 'NR'
        | 'NP'
        | 'BQ'
        | 'NL'
        | 'NC'
        | 'NZ'
        | 'NI'
        | 'NE'
        | 'NG'
        | 'NU'
        | 'NF'
        | 'MP'
        | 'NO'
        | 'OM'
        | 'PK'
        | 'PW'
        | 'PS'
        | 'PA'
        | 'PG'
        | 'PY'
        | 'PE'
        | 'PH'
        | 'PN'
        | 'PL'
        | 'PT'
        | 'PR'
        | 'QA'
        | 'RE'
        | 'RO'
        | 'RU'
        | 'RW'
        | 'SH'
        | 'KN'
        | 'LC'
        | 'PM'
        | 'VC'
        | 'BL'
        | 'MF'
        | 'WS'
        | 'SM'
        | 'ST'
        | 'SA'
        | 'SN'
        | 'RS'
        | 'SC'
        | 'SL'
        | 'SG'
        | 'SK'
        | 'SI'
        | 'SB'
        | 'SO'
        | 'ZA'
        | 'GS'
        | 'SS'
        | 'ES'
        | 'LK'
        | 'SD'
        | 'SR'
        | 'SJ'
        | 'SZ'
        | 'SE'
        | 'CH'
        | 'SY'
        | 'TW'
        | 'TJ'
        | 'TZ'
        | 'TH'
        | 'TG'
        | 'TK'
        | 'TO'
        | 'TT'
        | 'TN'
        | 'TR'
        | 'TM'
        | 'TC'
        | 'TV'
        | 'UG'
        | 'UA'
        | 'AE'
        | 'GB'
        | 'US'
        | 'UM'
        | 'UY'
        | 'UZ'
        | 'VU'
        | 'VA'
        | 'VE'
        | 'VN'
        | 'VG'
        | 'VI'
        | 'WF'
        | 'EH'
        | 'YE'
        | 'ZM'
        | 'ZW'
        | 'XK'
        | 'CW'
        | 'SX'
      )
    | null;
  state?: string | null;
  city?: string | null;
  companyUsers?: {
    docs?: (number | CompanyUser)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  msdsV2?: {
    docs?: (number | MsdsV2)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Use this to manage MSDS contents. "MSDS Files" and "MSDS Records" will be deprecated soon. Use MSDS v2 instead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "msdsV2".
 */
export interface MsdsV2 {
  /**
   * If not filled, it takes the name of the uploaded file.
   */
  name?: string | null;
  /**
   * Automatically generated after saving the document. (It is defined as: {company}-{name}-{id}-{contentLanguage})
   */
  uniqueId?: string | null;
  company: number | Company;
  /**
   * Determine whether the content can currently be displayed to the customer.
   */
  isPublished?: boolean | null;
  id: number;
  /**
   * If there are fields that are not filled, it will read them from the pdf file and fill them automatically.
   */
  aiScanning?: boolean | null;
  msdsCreatedAt?: string | null;
  formNo?: string | null;
  msdsUpdatedAt?: string | null;
  updatedCount?: number | null;
  author?: string | null;
  certificateDate?: string | null;
  /**
   * End of validity period for MSDS document (5 years after certificate date)
   */
  expiryDate?: string | null;
  contentLanguage?: (number | null) | ContentLanguage;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentLanguages".
 */
export interface ContentLanguage {
  id: number;
  name: string;
  code: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Used to manage MSDS requests.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "msdsRequests".
 */
export interface MsdsRequest {
  id: number;
  productName: string;
  company: number | Company;
  status: 'pending' | 'inProgress' | 'completed';
  sdsFile?: (number | null) | FileMedia;
  requestedBy: number | CompanyUser;
  responses?:
    | {
        message: string;
        respondedBy: number | AdminUser;
        respondedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Upload and manage SDS files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fileMedia".
 */
export interface FileMedia {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'adminUsers';
        value: number | AdminUser;
      } | null)
    | ({
        relationTo: 'companyUsers';
        value: number | CompanyUser;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'contentLanguages';
        value: number | ContentLanguage;
      } | null)
    | ({
        relationTo: 'msdsV2';
        value: number | MsdsV2;
      } | null)
    | ({
        relationTo: 'msdsRequests';
        value: number | MsdsRequest;
      } | null)
    | ({
        relationTo: 'fileMedia';
        value: number | FileMedia;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'adminUsers';
        value: number | AdminUser;
      }
    | {
        relationTo: 'companyUsers';
        value: number | CompanyUser;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'adminUsers';
        value: number | AdminUser;
      }
    | {
        relationTo: 'companyUsers';
        value: number | CompanyUser;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminUsers_select".
 */
export interface AdminUsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyUsers_select".
 */
export interface CompanyUsersSelect<T extends boolean = true> {
  email?: T;
  hashedPassword?: T;
  sendEmail?: T;
  registrationCompleted?: T;
  fullname?: T;
  personalPhoneNumber?: T;
  position?: T;
  company?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  companyName?: T;
  status?: T;
  email?: T;
  address?: T;
  phoneNumber?: T;
  taxNumber?: T;
  taxOffice?: T;
  tradeRegistryNumber?: T;
  mersisNumber?: T;
  country?: T;
  state?: T;
  city?: T;
  companyUsers?: T;
  msdsV2?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentLanguages_select".
 */
export interface ContentLanguagesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "msdsV2_select".
 */
export interface MsdsV2Select<T extends boolean = true> {
  name?: T;
  uniqueId?: T;
  company?: T;
  isPublished?: T;
  id?: T;
  aiScanning?: T;
  msdsCreatedAt?: T;
  formNo?: T;
  msdsUpdatedAt?: T;
  updatedCount?: T;
  author?: T;
  certificateDate?: T;
  expiryDate?: T;
  contentLanguage?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "msdsRequests_select".
 */
export interface MsdsRequestsSelect<T extends boolean = true> {
  productName?: T;
  company?: T;
  status?: T;
  sdsFile?: T;
  requestedBy?: T;
  responses?:
    | T
    | {
        message?: T;
        respondedBy?: T;
        respondedAt?: T;
        id?: T;
      };
  description?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fileMedia_select".
 */
export interface FileMediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}